alpha: 0.2
alpha_lr: 0.001
actor_lr : 0.001
critic_lr : 0.0005

custom_loss : 0.01

iterations: 2000
buffer_size: 1000000
max_frames: 1000000

steps_per_epoch: 1000
test_episodes: 3
stats_freq: 5
gamma: 0.99

update_batch_size: 100
random_frames: 1000
update_freq: 50
grad_steps: 50

log_all: True
obs_norm : False
unbiased_update : False

acm_batch_size: 100
acm_epochs: 1
acm_update_freq: 10000
acm_pre_train_epochs: 10
acm_pre_train_samples: 50000
acm_update_batches : 100
acm_lr : 0.001
verbose: 1

min_max_denormalize : True
denormalize_actor_out : True
acm_critic : True
norm_closs : True       
debug_mode : True
use_gpu: False



custom_loss_target : 0.2
custom_loss_lr : 0.0001
lagrangian_custom_loss : True
separate_custom_loss : False